org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.11
parchment_version=2025.12.20
loader_version=0.18.4

mod_version=1.2.0f-fabric+mc1.21.11
maven_group=com.github.ysbbbbbb
archives_base_name=kaleidoscopecookery

fabric_version=0.141.3+1.21.11
forge_config_api_port_version=21.11.1
jei_version=27.4.0.15
fdrf_version=1.21.11-3.4.3+refabricated
hwe_version = 9.4.0
